name: nextdavinci
favicon: null
layout_spectrum: 0.99265
typography_spectrum: 0.31795
title: Who is going to be the next DaVinci?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#b4b4b4'
    - '#757575'
    - '#373737'
    - '#b22828'
  brandStrength: 0.5
  lightness: 0.018145150737836957
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
